name: Release

on:
  push:
    branches:
      - main
    paths:
      - 'package.json'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
          registry-url: 'https://registry.npmjs.org'
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9.x'
      - name: Version Check
        id: check
        uses: EndBug/version-check@v2
      - name: Check Failed
        if: steps.check.outputs.changed == 'false'
        run: exit 1
      - name: Create tag
        uses: actions/github-script@v3
        with:
          github-token: ${{ github.token }}
          script: |
            github.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tags/v${{ steps.check.outputs.version }}",
              sha: context.sha
            })
      - name: Prebuild
        run: | # node-gyp 不支持交叉编译(#829) 要把不同机器 build 好的的汇总起来发布又很麻烦 如果用 prebuild 而不是 prebuildify 上传到 github 又有网络问题 还是只 build linux 好了
          npm i nan
          npm i prebuildify node-gyp -g
          prebuildify -t 12.0.0 -t 14.0.0 -t 16.0.0 --arch x64 --platform linux --strip
      - name: Publish
        run: |
          npx npm-packlist -s
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
